### ISSUE TITLE
Preferred divination mode is ignored by main entry point functions

### ISSUE THREAD

**Issue by wombatzus** [zzkt/i-ching#8]
> The preferred method can be set or customized via the variable `i-ching-divination-method`

Reading this from the README, I understand it to mean that I can set `i-ching-divination-method` and it should be automatically used when calling `i-ching-query` or `i-ching-cast` or similar functions, if I do not specify a method.  Instead, `i-ching-divination-method` is ignored and `i-ching-cast` uses `i-ching--random-number` instead (which never returns changing lines, which is what led me to figuring this out).

Requested: if no optional method param is passed, use method specified by `i-ching-divination-method` as default.

**Comment by zzkt** [comment]
Thanks @wombatzus it should be fixed with 54f19e2dcb1d16735b94fc7e06a2aa8b1b6f165a

**Comment by wombatzus** [comment]
Thank you very much!
